### ISSUE TITLE
TOC page numbers and "Page" label not right-justified

### ISSUE THREAD

**Issue by weiglemc** [oduwsdl/odusci-etd-template#1]
In the main Table of Contents, the page numbers and "Page" heading are not right-justified. These are formatted correctly in the List of Tables and List of Figures.

**Comment by weiglemc** [comment]
Real issue is that there are too many dot leaders and the page numbers are getting printed outside of the margin.

**Comment by himarshaj** [comment]
Reverted the changes to how it was. Issue fixed. 
![image](https://github.com/user-attachments/assets/0faec1fa-c3e0-45f2-b954-48a84aa0225b)
