### ISSUE TITLE
Add packages (url, listings) to style 

### ISSUE THREAD

**Issue by weiglemc** [oduwsdl/odusci-etd-template#2]
Add `url` and `listings` packages to the default style:
* `listings` is needed for code listings
* `url` is useful for formatting long URLs

**Comment by himarshaj** [comment]
Added to README and included examples in the LaTeX template.

Add URL as: \url{https://github.com/oduwsdl/odusci-etd-template/blob/main/README.md}
https://github.com/oduwsdl/odusci-etd-template/blob/4c212ed3b0600e9554cbd2442e2bbb8692019be8/Chapters/01_introduction.tex#L4C505-L4C605
