### ISSUE TITLE
LaTeX kernel fault with multi-file appendices

### ISSUE THREAD

**Issue by rot4te** [oduwsdl/odusci-etd-template#4]
using a \include{"...file..."} command after \appendix somehow puts the first included appendix file in the TOC before the appendix. The example puts all appendices in the same file with the \appendix command, but this isn't very elegant (e.g. my dissertation appendices A and B are each about 20 pages long, so I keep them separate).

I found a way to fix this problem by wrapping things in a custom environment. I'll make a pull request to show how it works.

**Comment by rot4te** [comment]
Or I would, if I were allowed.

**Comment by weiglemc** [comment]
Thanks for submitting this Issue.  I believe I've given you access to submit a PR.  Thanks!

**Comment by rot4te** [comment]
Thank you! I made the pull request.
There's probably a more elegant way to do what I've done, but it gets the job done.

**Comment by weiglemc** [comment]
Re-opening this issue so that we can review and double-check the impact of the PR -- must have gotten merged by mistake.

**Comment by himarshaj** [comment]
Revised the README and included examples in the LaTeX template. No issues with the PR. 

https://github.com/oduwsdl/odusci-etd-template/blob/4c212ed3b0600e9554cbd2442e2bbb8692019be8/main.tex#L127C1-L133C17
