### ISSUE TITLE
Test longtable package and add example

### ISSUE THREAD

**Issue by weiglemc** [oduwsdl/odusci-etd-template#6]
Add examples of longtable and landscape tables/figures.
https://www.overleaf.com/latex/examples/a-longtable-example/xxwzfxkxxjmc
https://ctan.org/pkg/longtable?lang=en

landscape - https://ctan.org/pkg/lscape?lang=en

**Comment by himarshaj** [comment]
Revised the README and included examples in the LaTeX template.

https://github.com/oduwsdl/odusci-etd-template/blob/main/Chapters/06_concordia.tex#L84
