### ISSUE TITLE
Change figure/table sizing examples

### ISSUE THREAD

**Issue by weiglemc** [oduwsdl/odusci-etd-template#7]
Make clear that images can be resized, use some percentage of `\linewidth` as an example

Comment from Maytha:

> Initially, I had to follow the specified LaTeX code strictly. For example, for figure sizes, the 4cm height in the template code:  
> ```latex
> \begin{figure}[tbh] 
>  \centering \includegraphics[height=4cm]{Figures/cos1.jpeg} 
>  \caption[The figure title goes here.]{The figure title goes here. Please describe the figure and figure legends here.}
>  \label{fig:cos1_1} 
> \end{figure}  
> ```
> 
> However, after my communication with you and Himarsha, I  realized that the figure size could be adjusted. Similarly, with the tables, I thought I could not change them, and I had to use precisely the provided setting. I believe it might be helpful to clarify this flexibility for future students, as it could save time and allow them to optimize the appearance of their figures and tables to best suit their content.

**Comment by himarshaj** [comment]
Revised the README and included examples in the LaTeX template.

https://github.com/oduwsdl/odusci-etd-template/blob/4c212ed3b0600e9554cbd2442e2bbb8692019be8/Chapters/02_background.tex#L28C1-L36C13
